

all :
	gcc -lmlx -framework OpenGL -framework AppKit ../parse_part1/file_parse1.c ../parse_part1/gnl/get_next_line.c ../parse_part1/gnl/get_next_line_utils.c ../parse_part1/file_error_fcts1.c ../parse_part1/utils1.c ../parse_part1/file_error_fcts2.c main.c ../parse_part1/file_texture_check.c ../parse_part1/utils2.c ../parse_part1/info_fcts1.c move_player.c ray_collision.c playerinfo_utils.c ray_casting.c load_color_from_texture.c
